db:
	python3 manage.py makemigrations
	python3 manage.py migrate

server:
	python3 manage.py runserver

All: 
	python3 manage.py makemigrations
	python3 manage.py migrate     
	python3 manage.py runserver      